// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package orders

import (
	"database/sql"
)

type Order struct {
	ID            int64         `json:"id"`
	PlatformID    int64         `json:"platform_id"`
	IsProcessed   int64         `json:"is_processed"`
	ProcessedDate sql.NullInt64 `json:"processed_date"`
	CreationDate  int64         `json:"creation_date"`
}
