// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package orders

import (
	"database/sql"
)

type Order struct {
	ID            int64         `json:"id"`
	PlatformID    string        `json:"platform_id"`
	OrderNumber   int64         `json:"order_number"`
	IsProcessed   int64         `json:"is_processed"`
	TotalPrice    float64       `json:"total_price"`
	CustomerName  string        `json:"customer_name"`
	ProcessedDate sql.NullInt64 `json:"processed_date"`
	CreationDate  int64         `json:"creation_date"`
}
