// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package orders

import (
	"context"
	"database/sql"
)

const addOrder = `-- name: AddOrder :one
INSERT INTO
    orders (platform_id, creation_date)
VALUES
    (?, ?) RETURNING id, platform_id, is_processed, processed_date, creation_date
`

type AddOrderParams struct {
	PlatformID   int64 `json:"platform_id"`
	CreationDate int64 `json:"creation_date"`
}

// CREATE TABLE orders (
//
//	id INTEGER PRIMARY KEY,
//	platform_id INTEGER UNIQUE NOT NULL,
//	is_processed INTEGER DEFAULT 0,
//	processed_date INTEGER DEFAULT 0,
//	creation_date INTEGER
//
// );
func (q *Queries) AddOrder(ctx context.Context, arg AddOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, addOrder, arg.PlatformID, arg.CreationDate)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PlatformID,
		&i.IsProcessed,
		&i.ProcessedDate,
		&i.CreationDate,
	)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM orders
WHERE
    id = ?
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAuthor, id)
	return err
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT
    id, platform_id, is_processed, processed_date, creation_date
FROM
    orders
`

func (q *Queries) GetAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PlatformID,
			&i.IsProcessed,
			&i.ProcessedDate,
			&i.CreationDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOrdersDescDate = `-- name: GetAllOrdersDescDate :many
SELECT
    id, platform_id, is_processed, processed_date, creation_date
FROM
    orders
ORDER BY
    creation_date DESC
`

func (q *Queries) GetAllOrdersDescDate(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrdersDescDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PlatformID,
			&i.IsProcessed,
			&i.ProcessedDate,
			&i.CreationDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrder = `-- name: GetOrder :one
SELECT
    id, platform_id, is_processed, processed_date, creation_date
FROM
    orders
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PlatformID,
		&i.IsProcessed,
		&i.ProcessedDate,
		&i.CreationDate,
	)
	return i, err
}

const getProcessedOrders = `-- name: GetProcessedOrders :many
SELECT
    id, platform_id, is_processed, processed_date, creation_date
FROM
    orders
WHERE
    is_processed = 1
ORDER BY
    processed_date DESC
`

// sorting latest
func (q *Queries) GetProcessedOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getProcessedOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PlatformID,
			&i.IsProcessed,
			&i.ProcessedDate,
			&i.CreationDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnProcessedOrders = `-- name: GetUnProcessedOrders :many
SELECT
    id, platform_id, is_processed, processed_date, creation_date
FROM
    orders
WHERE
    is_processed = 0
ORDER BY
    processed_date ASC
`

// sorting oldest
func (q *Queries) GetUnProcessedOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getUnProcessedOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PlatformID,
			&i.IsProcessed,
			&i.ProcessedDate,
			&i.CreationDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const processOrder = `-- name: ProcessOrder :one
UPDATE orders
SET
    is_processed = 1,
    processed_date = ?
WHERE
    id = ? RETURNING is_processed
`

type ProcessOrderParams struct {
	ProcessedDate sql.NullInt64 `json:"processed_date"`
	ID            int64         `json:"id"`
}

func (q *Queries) ProcessOrder(ctx context.Context, arg ProcessOrderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, processOrder, arg.ProcessedDate, arg.ID)
	var is_processed int64
	err := row.Scan(&is_processed)
	return is_processed, err
}

const unProcessOrder = `-- name: UnProcessOrder :one
UPDATE orders
SET
    is_processed = 0,
    processed_date = 0
WHERE
    id = ? RETURNING is_processed
`

func (q *Queries) UnProcessOrder(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, unProcessOrder, id)
	var is_processed int64
	err := row.Scan(&is_processed)
	return is_processed, err
}
